#!/bin/bash
################################################################################
#  Sample job script to run the BWA aligner on SDSC's Gordon Resource.  Note 
#  that this script assumes you have access to the shared queue on Gordon, which
#  requires a pre-arranged collaboration with SDSC.  Contact help@xsede.org if
#  you need guidance converting this script to a job suitable for the normal
#  queue.
#
#  Glenn K. Lockwood, San Diego Supercomputer Center             January 2014
################################################################################
#PBS -N gatk-baserecal
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=8:native:flash
#PBS -q shared
#PBS -v QOS=10
#PBS -m abe
#PBS -j oe
#PBS -o gatk-baserecal-samp1.out

BASE_DIR="/oasis/projects/nsf/abc123/$USER/sample1"
REF_DIR="/oasis/projects/nsf/abc123/$USER/reference"

module load biotools

cd $PBS_O_WORKDIR

/usr/java/latest/bin/java -Xmx20g \
    -Djava.io.tmpdir=/scratch/$USER/$PBS_JOBID \
    -jar $GATKHOME/GenomeAnalysisTK.jar \
    -T BaseRecalibrator \
    -R $REF_DIR/hg19.fa \
    -I $BASE_DIR/sample1.bam \
    -knownSites $REF_DIR/dbsnp_137.b37.vcf \
    -knownSites $REF_DIR/Mills_and_1000G_gold_standard.indels.b37.vcf \
    -nct 8 \
    -o $BASE_DIR/sample1_recal.table

/opt/torque/bin/qstat -f $PBS_JOBID | /bin/grep -e Job -e resources
